import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./component/footer/Footer";
import Navbar from "./component/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eticaret",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex  flex-col min-h-screen">
          <Footer />
          <main className="flex-grow ">{children}</main>
          <Navbar />
        </div>
      </body>
    </html>
  );
}
